name: cursonet_workflow
on:
  push:
     branches: [ master ]

jobs:
  job_one:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
      - name: deploying garafy project
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.CURSONET_SERVER_IP}}
          username: ${{secrets.CURSONET_SERVER_USER}}
          key:  ${{secrets.CURSONET_SERVER_SECRET}}
          port: 22
          script: |
            cd /var/www/html/cursonet2.0/
            git checkout .
            git pull origin master
            composer install
            php artisan cache:clear
            npm install
            npm run prod
